coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch: false
    changes: false
    ignore:
      - "pulse2percept/datasets/tests/**/*"
      - "pulse2percept/implants/tests/**/*"
      - "pulse2percept/model_selection/tests/**/*"
      - "pulse2percept/models/tests/**/*"
      - "pulse2percept/percepts/tests/**/*"
      - "pulse2percept/stimuli/tests/**/*"
      - "pulse2percept/utils/tests/**/*"
      - "pulse2percept/viz/tests/**/*"