version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  environment:
    P2P_DISABLE_OPENMP: "1"   # let setup.py skip -fopenmp on RTD
sphinx:
  configuration: doc/conf.py
python:
  install:
    - requirements: doc/requirements-docs.txt
    - method: pip
      path: .
