version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: doc/conf.py
  fail_on_warning: false
  builder: html

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
