# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-latest
  tools:
    python: "3.11"

sphinx:
  configuration: doc/conf.py
  fail_on_warning: true
  builder: "html"

formats:
  - pdf
  - epub

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
