# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.11"

sphinx:
  configuration: doc/conf.py
  fail_on_warning: false
  builder: "html"

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
