version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.11"
  environment:
    P2P_PLOT_GALLERY: "0"
    P2P_DOC_BUILD: "1"

sphinx:
  configuration: doc/conf.py
  fail_on_warning: false
  builder: "html"

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
