name: Colab-ish PR install smoke

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  colab_smoke:
    name: Colab-ish • py${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.12"]  # keep aligned with Colab

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install build toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gfortran libomp-dev

      - name: Create venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip setuptools wheel

      - name: Install from VCS (verbose)
        env: { PIP_NO_INPUT: "1" }
        run: |
          source .venv/bin/activate
          python -m pip install -v "${{ steps.vcs.outputs.url }}"
          python -m pip install packaging

      - name: Verify runtime deps
        run: |
          source .venv/bin/activate
          python .github/scripts/verify_runtime_deps.py
          python -m pip check

      - name: Assert C-extension presence
        run: |
          source .venv/bin/activate
          python - <<'PY'
          import pathlib, pulse2percept as p2p
          utils_dir = pathlib.Path(p2p.__file__).with_name("utils")
          so = list(utils_dir.glob("_fast_array*.so"))
          print("utils_dir:", utils_dir)
          print("compiled:", [s.name for s in so])
          PY

      - name: Smoke import (minimal path)
        run: |
          source .venv/bin/activate
          python - <<'PY'
          from pulse2percept.models import ScoreboardModel
          _ = ScoreboardModel().build()
          print("Smoke OK")
          PY
