name: Colab-ish daily install drift

on:
  schedule:
    - cron: "13 7 * * *"   # daily at 07:13 UTC
  workflow_dispatch: {}

jobs:
  drift:
    name: ${{ matrix.channel }} • py${{ matrix.python }} • ${{ matrix.profile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.12"]                    # Colab: Python 3.12.11 currently
        channel: ["git-master", "pypi-stable"]
        profile: ["latest", "colab-pins"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install build toolchain (gcc, OpenMP, Fortran)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gfortran libomp-dev pkg-config

      - name: Create venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip setuptools wheel packaging

      - name: (Optional) Pre-pin Colab packages
        if: matrix.profile == 'colab-pins'
        env:
          PIP_NO_INPUT: "1"
        run: |
          source .venv/bin/activate
          # Colab pins live in .github/colab-pins.txt; PyTorch CUDA index for cu126
          python -m pip install -r .github/colab-pins.txt --index-url https://download.pytorch.org/whl/cu126
          python - <<'PY'
          import importlib, sys
          for m in ["numpy","jax","jaxlib","tensorflow","torch","torchvision","torchaudio"]:
              try:
                  mod = importlib.import_module(m)
                  print(f"{m}=={getattr(mod,'__version__','?')}")
              except Exception as e:
                  print(f"{m} import failed: {e}")
          print(sys.version)
          PY

      - name: Install pulse2percept (${{ matrix.channel }})
        env:
          PIP_NO_INPUT: "1"
        run: |
          source .venv/bin/activate
          if [ "${{ matrix.channel }}" = "git-master" ]; then
            TARGET="git+https://github.com/pulse2percept/pulse2percept"
          else
            TARGET="pulse2percept"
          fi
          echo "Installing: $TARGET"
          python -m pip install "$TARGET"

      - name: Verify runtime deps from installed metadata
        run: |
          source .venv/bin/activate
          python .github/scripts/verify_runtime_deps.py
          python -m pip check

      - name: Assert compiled C-extension artifact exists (non-fatal log)
        continue-on-error: true
        run: |
          source .venv/bin/activate
          python - <<'PY'
          import pathlib, importlib
          import pulse2percept as p2p
          utils_dir = pathlib.Path(p2p.__file__).with_name("utils")
          arts = list(utils_dir.glob("_fast_array*.so")) + list(utils_dir.glob("_fast_array*.pyd"))
          print("utils_dir:", utils_dir)
          print("compiled artifacts:", [a.name for a in arts])
          PY

      - name: Smoke import (minimal path)
        run: |
          source .venv/bin/activate
          python - <<'PY'
          from pulse2percept.models import ScoreboardModel
          _ = ScoreboardModel().build()
          print("Smoke OK")
          PY
